// 内置模板库（方案 §11）+ 默认各 scope 排序
// 约定：关键字类缩写（def/class/if/for/...）tabExpand=false，仅走补全弹窗，避免与正常编码冲突；
//       非冲突缩写 tabExpand=true，支持「缩写+Tab」直接展开。
// i18n（第十九批）：description / group 为展示文案（补全弹窗、管理面板、环绕/后缀选择器）——
//       构建函数 + let + onLocaleChange 重建（⑧/⑮ 模式）；局部构建 helper 改名 tpl 避让 i18n t()。

import { onLocaleChange, t } from "../i18n";
import type { TemplateDef } from "./schema";

const PY_ALL = ["python:module", "python:class", "python:function"];
const PY_CLASS = ["python:class"];
const PY_CLASS_FN = ["python:class", "python:function"];

const tpl = (partial: Omit<TemplateDef, "kind" | "enabled"> & Partial<Pick<TemplateDef, "kind" | "enabled">>): TemplateDef => ({
  kind: "normal",
  enabled: true,
  ...partial,
});

function buildBuiltinTemplates(): TemplateDef[] {
  return [
  tpl({
    id: "builtin.main",
    abbreviation: "main",
    description: t("lt.tpl.main"),
    body: "def main($ARGS$):\n    $END$",
    // 模块层 + 语句位：定义入口函数；守卫改由 ifmain 承担（用户反馈 2026-08-26）
    scopes: ["python:module"],
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "ARGS" }],
  }),
  tpl({
    id: "builtin.ifmain",
    // 别名缩写：避开高频标识符 main 的快捷通道（产品裁决 2026-08-26 保留）
    abbreviation: "ifmain",
    description: "if __name__ == '__main__'",
    body: 'if __name__ == "__main__":\n    $END$',
    scopes: ["python:module"],
    positions: ["statement"],
    tabExpand: true,
  }),
  tpl({
    id: "builtin.def",
    abbreviation: "def",
    description: t("lt.tpl.def"),
    body: "def $NAME$($ARGS$):\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "NAME", defaultValue: "name" }, { name: "ARGS" }],
  }),
  tpl({
    id: "builtin.class",
    abbreviation: "class",
    description: t("lt.tpl.class"),
    body: "class $NAME$:\n    def __init__(self$ARGS$):\n        $END$",
    scopes: ["python:module", "python:class"],
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "NAME", defaultValue: "Name" }, { name: "ARGS", defaultValue: ", *args" }],
  }),
  tpl({
    id: "builtin.dataclass",
    abbreviation: "dataclass",
    description: t("lt.tpl.dataclass"),
    body: "@dataclass\nclass $NAME$:\n    $END$",
    scopes: ["python:module", "python:class"],
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "NAME", defaultValue: "Name" }],
  }),
  tpl({
    id: "builtin.if",
    abbreviation: "if",
    description: t("lt.tpl.if"),
    body: "if $COND$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "COND", defaultValue: "condition" }],
  }),
  tpl({
    id: "builtin.ife",
    abbreviation: "ife",
    description: t("lt.tpl.ife"),
    body: "if $COND$:\n    $THEN$\nelse:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "COND", defaultValue: "condition" }, { name: "THEN", defaultValue: "pass" }],
  }),
  tpl({
    id: "builtin.for",
    abbreviation: "for",
    description: t("lt.tpl.for"),
    body: "for $ITEM$ in $ITERABLE$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "ITEM", defaultValue: "item" }, { name: "ITERABLE", defaultValue: "items" }],
  }),
  tpl({
    id: "builtin.while",
    abbreviation: "while",
    description: t("lt.tpl.while"),
    body: "while $COND$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "COND", defaultValue: "condition" }],
  }),
  tpl({
    id: "builtin.try",
    abbreviation: "try",
    description: t("lt.tpl.try"),
    body: "try:\n    $BODY$\nexcept $EXC$ as $E$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [
      { name: "BODY" },
      {
        name: "EXC",
        expression: 'enum("Exception", "ValueError", "KeyError", "TypeError", "OSError")',
        defaultValue: "Exception",
      },
      { name: "E", defaultValue: "e" },
    ],
  }),
  tpl({
    id: "builtin.with",
    abbreviation: "with",
    description: t("lt.tpl.with"),
    body: "with $EXPR$ as $ALIAS$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: false,
    variables: [{ name: "EXPR", defaultValue: 'open("file")' }, { name: "ALIAS", defaultValue: "f" }],
  }),
  tpl({
    id: "builtin.lambda",
    abbreviation: "lambda",
    description: t("lt.tpl.lambda"),
    body: "lambda $ARGS$: $EXPR$",
    scopes: PY_ALL,
    tabExpand: false,
    variables: [{ name: "ARGS", defaultValue: "x" }, { name: "EXPR", defaultValue: "x" }],
  }),
  tpl({
    id: "builtin.print",
    abbreviation: "print",
    description: t("lt.tpl.print"),
    body: "print($END$)",
    scopes: PY_ALL,
    tabExpand: true,
  }),
  tpl({
    id: "builtin.super",
    abbreviation: "super",
    description: "super().__init__(...)",
    body: "super().__init__($END$)",
    scopes: PY_CLASS_FN,
    tabExpand: true,
  }),
  tpl({
    id: "builtin.init",
    abbreviation: "init",
    description: t("lt.tpl.init"),
    body: "def __init__(self$ARGS$):\n    $END$",
    scopes: PY_CLASS,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "ARGS" }],
  }),
  tpl({
    id: "builtin.prop",
    abbreviation: "prop",
    description: "@property getter",
    body: "@property\ndef $NAME$(self):\n    return $END$",
    scopes: PY_CLASS,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "NAME", defaultValue: "name" }],
  }),
  tpl({
    id: "builtin.iter",
    abbreviation: "iter",
    description: t("lt.tpl.iter"),
    body: "def __iter__(self):\n    $FIRST$\n\ndef __next__(self):\n    $END$",
    scopes: PY_CLASS,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "FIRST", defaultValue: "return self" }],
  }),
  tpl({
    id: "builtin.repr",
    abbreviation: "repr",
    description: t("lt.tpl.repr"),
    body: "def __repr__(self):\n    return $END$",
    scopes: PY_CLASS,
    positions: ["statement"],
    tabExpand: true,
  }),
  // P2（PyCharm 调研 E4）：docstring 三件套。
  // 关键点是 `allowInStrings: true`——docstring 本身就在字符串字面量里，
  // 而 tabExpand 默认**禁止**字符串内展开（tabExpand.ts:93），不显式开启等价于永远用不上。
  tpl({
    id: "builtin.doc",
    abbreviation: "doc",
    description: t("lt.tpl.doc"),
    body: '"""$DESC$$END$"""',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    allowInStrings: true,
    variables: [{ name: "DESC", defaultValue: "TODO" }],
  }),
  tpl({
    id: "builtin.docf",
    abbreviation: "docf",
    description: t("lt.tpl.docf"),
    body: '"""$DESC$\n\n    Args:\n        $ARG$: $ARGDESC$\n\n    Returns:\n        $END$\n    """',
    scopes: PY_CLASS_FN,
    positions: ["statement"],
    tabExpand: true,
    allowInStrings: true,
    variables: [
      { name: "DESC", defaultValue: "TODO" },
      { name: "ARG", defaultValue: "name" },
      { name: "ARGDESC", defaultValue: t("lt.tpl.argDescDefault") },
    ],
  }),
  tpl({
    id: "builtin.docc",
    abbreviation: "docc",
    description: t("lt.tpl.docc"),
    body: '"""$DESC$\n\n    Attributes:\n        $ATTR$: $END$\n    """',
    scopes: PY_CLASS,
    positions: ["statement"],
    tabExpand: true,
    allowInStrings: true,
    variables: [
      { name: "DESC", defaultValue: "TODO" },
      { name: "ATTR", defaultValue: "name" },
    ],
  }),
  tpl({
    id: "builtin.header",
    abbreviation: "header",
    description: t("lt.tpl.header"),
    body: "# -*- coding: utf-8 -*-\n# $FILE$ — $DESC$\n# Author: $USER$\n# Date: $DATE$\n$END$",
    scopes: ["python:module"],
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "FILE", expression: "fileName()", skipIfDefined: true },
      { name: "DESC", defaultValue: "TODO" },
      { name: "USER", expression: "user()", skipIfDefined: true },
      { name: "DATE", expression: 'date("yyyy-MM-dd")', skipIfDefined: true },
    ],
  }),

  // async 三件套（M4 内置库补齐）
  tpl({
    id: "builtin.adef",
    abbreviation: "adef",
    description: t("lt.tpl.adef"),
    body: "async def $NAME$($ARGS$):\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "NAME", defaultValue: "name" }, { name: "ARGS" }],
  }),
  tpl({
    id: "builtin.afor",
    abbreviation: "afor",
    description: t("lt.tpl.afor"),
    body: "async for $ITEM$ in $ITERABLE$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "ITEM", defaultValue: "item" }, { name: "ITERABLE", defaultValue: "items" }],
  }),
  tpl({
    id: "builtin.awith",
    abbreviation: "awith",
    description: t("lt.tpl.awith"),
    body: "async with $EXPR$ as $ALIAS$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "EXPR", defaultValue: "aopen(\"file\")" }, { name: "ALIAS", defaultValue: "f" }],
  }),

  // ---------- 爬虫模板库（C 组：爬虫开发脚手架；均为语句位、可 Tab 展开） ----------
  // 请求（requests / httpx）
  tpl({
    id: "builtin.reqget",
    group: t("lt.group.crawler"),
    abbreviation: "reqget",
    description: t("lt.tpl.reqget"),
    body: "resp = requests.get($URL$, headers=$HEADERS$, timeout=$TIMEOUT$)\nresp.raise_for_status()\n$END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "URL", defaultValue: '"https://example.com"' },
      { name: "HEADERS", defaultValue: "headers" },
      { name: "TIMEOUT", defaultValue: "10" },
    ],
  }),
  tpl({
    id: "builtin.reqpost",
    group: t("lt.group.crawler"),
    abbreviation: "reqpost",
    description: t("lt.tpl.reqpost"),
    body: "resp = requests.post($URL$, json=$PAYLOAD$, headers=$HEADERS$, timeout=$TIMEOUT$)\nresp.raise_for_status()\n$END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "URL", defaultValue: '"https://example.com/api"' },
      { name: "PAYLOAD", defaultValue: "payload" },
      { name: "HEADERS", defaultValue: "headers" },
      { name: "TIMEOUT", defaultValue: "10" },
    ],
  }),
  tpl({
    id: "builtin.reqsess",
    group: t("lt.group.crawler"),
    abbreviation: "reqsess",
    description: t("lt.tpl.reqsess"),
    body: 'session = requests.Session()\nretries = Retry(total=$TOTAL$, backoff_factor=$BACKOFF$, status_forcelist=[429, 500, 502, 503, 504])\nsession.mount("https://", HTTPAdapter(max_retries=retries))\nsession.mount("http://", HTTPAdapter(max_retries=retries))\nsession.headers.update($HEADERS$)\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "TOTAL", defaultValue: "5" },
      { name: "BACKOFF", defaultValue: "0.5" },
      { name: "HEADERS", defaultValue: "headers" },
    ],
  }),
  tpl({
    id: "builtin.hget",
    group: t("lt.group.crawler"),
    abbreviation: "hget",
    description: t("lt.tpl.hget"),
    body: "async with httpx.AsyncClient(headers=$HEADERS$, timeout=$TIMEOUT$) as client:\n    resp = await client.get($URL$)\n    resp.raise_for_status()\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "URL", defaultValue: '"https://example.com"' },
      { name: "HEADERS", defaultValue: "headers" },
      { name: "TIMEOUT", defaultValue: "10" },
    ],
  }),
  // 解析（bs4 / lxml / JSON）
  tpl({
    id: "builtin.bs4",
    group: t("lt.group.crawler"),
    abbreviation: "bs4",
    description: t("lt.tpl.bs4"),
    body: 'soup = BeautifulSoup($HTML$, "$PARSER$")\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "HTML", defaultValue: "resp.text" },
      { name: "PARSER", expression: 'enum("lxml", "html.parser")', defaultValue: "lxml" },
    ],
  }),
  tpl({
    id: "builtin.lxml",
    group: t("lt.group.crawler"),
    abbreviation: "lxml",
    description: t("lt.tpl.lxml"),
    body: "tree = etree.HTML($HTML$)\n$RESULT$ = tree.xpath($XPATH$)\n$END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "HTML", defaultValue: "resp.text" },
      { name: "RESULT", defaultValue: "items" },
      { name: "XPATH", defaultValue: '"//div"' },
    ],
  }),
  tpl({
    id: "builtin.css",
    group: t("lt.group.crawler"),
    abbreviation: "css",
    description: t("lt.tpl.css"),
    body: "$ITEMS$ = soup.select($SELECTOR$)\nfor $ITEM$ in $ITEMS$:\n    $END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "ITEMS", defaultValue: "items" },
      { name: "SELECTOR", defaultValue: '".item"' },
      { name: "ITEM", defaultValue: "item" },
    ],
  }),
  tpl({
    id: "builtin.jsonld",
    group: t("lt.group.crawler"),
    abbreviation: "jsonld",
    description: t("lt.tpl.jsonld"),
    body: "data = $RESP$.json()\n$RESULT$ = data[$KEY$]\n$END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "RESP", defaultValue: "resp" },
      { name: "RESULT", defaultValue: "items" },
      { name: "KEY", defaultValue: '"data"' },
    ],
  }),
  // 翻页
  tpl({
    id: "builtin.page",
    group: t("lt.group.crawler"),
    abbreviation: "page",
    description: t("lt.tpl.page"),
    body: 'page = $START$\nwhile True:\n    resp = requests.get($URL$, params={"page": page}, timeout=$TIMEOUT$)\n    items = $PARSE$\n    if not items:\n        break\n    $END$\n    page += 1',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "START", defaultValue: "1" },
      { name: "URL", defaultValue: "url" },
      { name: "TIMEOUT", defaultValue: "10" },
      { name: "PARSE", defaultValue: "parse_page(resp)" },
    ],
  }),
  // 反爬（UA / 代理 / 限速）
  tpl({
    id: "builtin.ua",
    group: t("lt.group.crawler"),
    abbreviation: "ua",
    description: t("lt.tpl.ua"),
    body: 'USER_AGENTS = [\n    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",\n    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",\n]\nheaders = {"User-Agent": random.choice(USER_AGENTS)}\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
  }),
  tpl({
    id: "builtin.proxy",
    group: t("lt.group.crawler"),
    abbreviation: "proxy",
    description: t("lt.tpl.proxy"),
    body: 'proxies = {\n    "http": "$HTTP_PROXY$",\n    "https": "$HTTPS_PROXY$",\n}\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "HTTP_PROXY", defaultValue: "http://127.0.0.1:7890" },
      { name: "HTTPS_PROXY", defaultValue: "http://127.0.0.1:7890" },
    ],
  }),
  tpl({
    id: "builtin.rsleep",
    group: t("lt.group.crawler"),
    abbreviation: "rsleep",
    description: t("lt.tpl.rsleep"),
    body: "time.sleep(random.uniform($LO$, $HI$))\n$END$",
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "LO", defaultValue: "1" }, { name: "HI", defaultValue: "3" }],
  }),
  // 数据落地（CSV / JSON）
  tpl({
    id: "builtin.csvw",
    group: t("lt.group.crawler"),
    abbreviation: "csvw",
    description: t("lt.tpl.csvw"),
    body: 'with open($PATH$, "w", newline="", encoding="utf-8") as f:\n    writer = csv.DictWriter(f, fieldnames=$FIELDS$)\n    writer.writeheader()\n    writer.writerows($ROWS$)\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [
      { name: "PATH", defaultValue: '"data.csv"' },
      { name: "FIELDS", defaultValue: '["id", "title"]' },
      { name: "ROWS", defaultValue: "rows" },
    ],
  }),
  tpl({
    id: "builtin.jsonw",
    group: t("lt.group.crawler"),
    abbreviation: "jsonw",
    description: t("lt.tpl.jsonw"),
    body: 'with open($PATH$, "w", encoding="utf-8") as f:\n    json.dump($DATA$, f, ensure_ascii=False, indent=2)\n$END$',
    scopes: PY_ALL,
    positions: ["statement"],
    tabExpand: true,
    variables: [{ name: "PATH", defaultValue: '"data.json"' }, { name: "DATA", defaultValue: "data" }],
  }),

  // ---------- 环绕模板（M3，Ctrl+Alt+T；$SELECTION$ 承载选区） ----------
  tpl({
    id: "builtin.surround.q",
    abbreviation: "q",
    description: t("lt.tpl.surroundQuote"),
    body: '"$SELECTION$"$END$',
    scopes: PY_ALL,
    kind: "surround",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.surround.try",
    abbreviation: "try",
    description: t("lt.tpl.surroundTry"),
    body: "try:\n    $SELECTION$\nexcept $EXC$ as $E$:\n    $END$",
    scopes: PY_ALL,
    kind: "surround",
    tabExpand: false,
    variables: [
      {
        name: "EXC",
        expression: 'enum("Exception", "ValueError", "KeyError", "TypeError", "OSError")',
        defaultValue: "Exception",
      },
      { name: "E", defaultValue: "e" },
    ],
  }),
  tpl({
    id: "builtin.surround.if",
    abbreviation: "if",
    description: t("lt.tpl.surroundIf"),
    body: "if $COND$:\n    $SELECTION$\n$END$",
    scopes: PY_ALL,
    kind: "surround",
    tabExpand: false,
    variables: [{ name: "COND", defaultValue: "condition" }],
  }),
  tpl({
    id: "builtin.surround.with",
    abbreviation: "with",
    description: t("lt.tpl.surroundWith"),
    body: "with $EXPR$ as $ALIAS$:\n    $SELECTION$\n$END$",
    scopes: PY_ALL,
    kind: "surround",
    tabExpand: false,
    variables: [{ name: "EXPR", defaultValue: 'open("file")' }, { name: "ALIAS", defaultValue: "f" }],
  }),

  // ---------- 后缀模板（M3，`表达式.键` + 补全接受；$EXPR$ 由提取的表达式字面注入） ----------
  tpl({
    id: "builtin.postfix.if",
    abbreviation: "if",
    description: t("lt.tpl.postfixIf"),
    body: "if $EXPR$:\n    $END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "if",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.else",
    abbreviation: "else",
    description: t("lt.tpl.postfixElse"),
    body: "if not $EXPR$:\n    $END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "else",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.for",
    abbreviation: "for",
    description: t("lt.tpl.postfixFor"),
    body: "for $ITEM$ in $EXPR$:\n    $END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "for",
    tabExpand: false,
    variables: [{ name: "ITEM", defaultValue: "item" }],
  }),
  tpl({
    id: "builtin.postfix.try",
    abbreviation: "try",
    description: t("lt.tpl.surroundTry"),
    body: "try:\n    $EXPR$\nexcept $EXC$ as $E$:\n    $END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "try",
    tabExpand: false,
    variables: [
      {
        name: "EXC",
        expression: 'enum("Exception", "ValueError", "KeyError", "TypeError", "OSError")',
        defaultValue: "Exception",
      },
      { name: "E", defaultValue: "e" },
    ],
  }),
  tpl({
    id: "builtin.postfix.not",
    abbreviation: "not",
    description: t("lt.tpl.postfixNot"),
    body: "not $EXPR$$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "not",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.print",
    abbreviation: "print",
    description: t("lt.tpl.postfixPrint"),
    body: "print($EXPR$)$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "print",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.len",
    abbreviation: "len",
    description: t("lt.tpl.postfixLen"),
    body: "len($EXPR$)$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "len",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.return",
    abbreviation: "return",
    description: t("lt.tpl.postfixReturn"),
    body: "return $EXPR$$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "return",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.str",
    abbreviation: "str",
    description: t("lt.tpl.postfixStr"),
    body: "str($EXPR$)$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "str",
    tabExpand: false,
  }),
  tpl({
    id: "builtin.postfix.int",
    abbreviation: "int",
    description: t("lt.tpl.postfixInt"),
    body: "int($EXPR$)$END$",
    scopes: PY_ALL,
    kind: "postfix",
    postfixKey: "int",
    tabExpand: false,
  }),
  ];
}

export let BUILTIN_TEMPLATES: TemplateDef[] = buildBuiltinTemplates();

onLocaleChange(() => {
  BUILTIN_TEMPLATES = buildBuiltinTemplates(); // 语言切换：重建模板描述/group（⑧/⑮ 模式）
});

/** 默认各 scope 补全排序（下标 0 = preselect）；用户配置按 scope 键覆盖 */
export const BUILTIN_ORDERING: Record<string, string[]> = {
  "python:module": [
    "main", "ifmain", "def", "class", "dataclass", "if", "ife", "for", "while",
    // P2：模块层用单行 doc（`doc`）；`docf` 带 Args/Returns，只对函数/类有意义，
    // 故从模块层的排序里移除（scopes 已不再含 python:module，留着会让 ordering 校验失败）
    "try", "with", "print", "lambda", "header", "doc",
    // 爬虫脚手架（C 组）
    "reqget", "reqpost", "reqsess", "hget", "bs4", "lxml", "css", "jsonld",
    "page", "ua", "proxy", "rsleep", "csvw", "jsonw",
  ],
  "python:class": [
    "def", "init", "prop", "iter", "repr", "super", "class", "dataclass",
    "for", "try", "if", "ife", "with", "print", "docc", "doc",
  ],
  "python:function": [
    "for", "if", "ife", "try", "with", "while", "print",
    "lambda", "super", "docf", "doc", "def",
    // 爬虫脚手架（C 组）
    "reqget", "reqpost", "reqsess", "hget", "bs4", "lxml", "css", "jsonld",
    "page", "ua", "proxy", "rsleep", "csvw", "jsonw",
  ],
};
